### ISSUE TITLE
-

### ISSUE THREAD

**Issue by beingabstrac** [justmarkup/html-posts-to-markdown#1]
.

**Comment by justmarkup** [comment]
Hey @beingabstrac 

Can you send me the URL of the webpage, so I can have a look?

**Comment by beingabstrac** [comment]
Hi @justmarkup 

It's [Figma plugins](https://www.figma.com/community/plugin/all). Extract data from each plugin (name, description, plugin logo, header image) and store with `plugin-name` as the file name. Download images and store locally.

Example .yml configuration

![image](https://user-images.githubusercontent.com/11329634/79043284-e4a1ed80-7c1b-11ea-829a-3f6921d80c65.png)

**Comment by justmarkup** [comment]
Hey @beingabstrac 

This is code is not meant to be a scraper for third-party content, but do make it easier to move from one blog (in my case wordpress) to a static site generator, so I am afraid I can't help you here - there are lots of scrapers available which should do the job for you.
